name: CI - Tests

on:
    push:
        branches: [ "master" ]
    pull_request: ~

permissions:
    contents: read

jobs:
    ci-tests:
        runs-on: ubuntu-latest
        steps:
            #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
            # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
            - uses: actions/checkout@v3
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Start docker compose
              run: docker-compose up -d
            - name: create database
              run: symfony console doctrine:migrations:migrate -n
            - name: load fixtures
              run: symfony console doctrine:fixtures:load
            - name: Execute tests
              run: php bin/phpunit

