name: CI - Tests

on:
    push:
        branches: [ "master" ]
    pull_request: ~

permissions:
    contents: read

jobs:
    ci-tests:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16.1
                env:
                    POSTGRES_USER: 'mp_api'
                    POSTGRES_PASSWORD: 'mp_api'
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports: [ '5432:5432' ]
        steps:
            #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
            # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: symfony-cli
            - uses: actions/checkout@v3
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#            - name: Start docker compose
#              run: docker-compose up -d
            - name: create database
              run: symfony console doctrine:database:create
            - name: run migrations
              run: symfony console doctrine:migrations:migrate -n
            - name: load fixtures
              run: symfony console doctrine:fixtures:load -n
            - name: Execute tests
              run: php bin/phpunit

